# Generated by Django 5.1.1 on 2024-09-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('planId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('planName', models.CharField(default='Default plan name', max_length=200)),
                ('benefitType', models.CharField(default='Extra Voucher', max_length=50)),
                ('benefitPercentage', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('promoId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('planId', models.IntegerField(default=0)),
                ('promoName', models.CharField(default='Default promo name', max_length=200)),
            ],
        ),
    ]
