# Generated by Django 5.1.1 on 2024-09-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='planId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promoId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
