# Generated by Django 5.1.1 on 2024-09-10 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_plan_planid_alter_promo_promoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='amountOptions',
            field=models.JSONField(default=[10000, 20000, 50000], editable=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='tenureOptions',
            field=models.JSONField(default=[6, 12, 24], editable=False),
        ),
        migrations.AddField(
            model_name='promo',
            name='benefitPercentage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='promo',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='validityType',
            field=models.CharField(choices=[('quantity', 'Quantity'), ('tenure', 'Tenure')], default='quantity', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefitType',
            field=models.CharField(choices=[('voucher', 'Voucher'), ('cashback', 'Cashback')], default='voucher', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='planName',
            field=models.CharField(default='This is not a valid plan. Allow us some time to fix this!', max_length=500),
        ),
        migrations.AlterField(
            model_name='promo',
            name='planId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Promotions', to='api.plan'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promoName',
            field=models.CharField(default='This is not a valid promo. Allow us some time to fix this!', max_length=500),
        ),
    ]
