# Generated by Django 5.1.1 on 2024-09-10 19:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plan_amountoptions_plan_tenureoptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amountOptions',
            field=models.JSONField(default=api.models.default_amount_options, editable=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tenureOptions',
            field=models.JSONField(default=api.models.default_tenure_options, editable=False),
        ),
    ]
