# Generated by Django 5.1.1 on 2024-09-10 21:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_plan_amountoptions_alter_plan_tenureoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=200)),
                ('userMail', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='promo',
            name='planId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='api.plan'),
        ),
        migrations.CreateModel(
            name='UserSelectedPlans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promoID', models.IntegerField()),
                ('selectedAmount', models.IntegerField(null=True)),
                ('selectedTenure', models.IntegerField(null=True)),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('depositedAmount', models.IntegerField(default=0)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
